server:
  port: 8080
  address: 0.0.0.0

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456


  security:
    user:
      name: 18070960411
      password: 123456


mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.ztj.hcboot.pojo
  configuration:
    map-underscore-to-camel-case: true




